# Generated by Django 5.2.7 on 2026-02-02 10:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("alternative_phone", models.CharField(blank=True, max_length=20)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Uganda", max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "icpau_registration_number",
                    models.CharField(
                        blank=True, help_text="ICPAU Registration Number", max_length=50
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Areas of specialization, comma-separated"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture (max 5MB, recommended: 400x400px)",
                        null=True,
                        upload_to="profile_pictures/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief professional biography",
                        max_length=1000,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("linkedin_profile", models.URLField(blank=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("lg", "Luganda"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="Africa/Kampala", max_length=50)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members_only", "Members Only"),
                            ("private", "Private"),
                        ],
                        default="members_only",
                        max_length=20,
                    ),
                ),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("newsletter_subscription", models.BooleanField(default=True)),
                ("event_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Profile Created"),
                            ("updated", "Profile Updated"),
                            ("picture_uploaded", "Picture Uploaded"),
                            ("picture_removed", "Picture Removed"),
                            ("privacy_changed", "Privacy Settings Changed"),
                            (
                                "notifications_changed",
                                "Notification Preferences Changed",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_changed", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Activity Log",
                "verbose_name_plural": "Profile Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
