import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api.settings')
django.setup()

from django.db import connection

# SQL to create authentication tables
sql_statements = [
    """CREATE TABLE IF NOT EXISTS "auth_users" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "password" varchar(128) NOT NULL,
        "last_login" timestamp with time zone NULL,
        "is_superuser" boolean NOT NULL,
        "email" varchar(254) NOT NULL UNIQUE,
        "role" varchar(10) NOT NULL,
        "is_active" boolean NOT NULL,
        "is_staff" boolean NOT NULL,
        "created_at" timestamp with time zone NOT NULL,
        "updated_at" timestamp with time zone NOT NULL
    )""",
    
    """CREATE TABLE IF NOT EXISTS "auth_users_groups" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "group_id" integer NOT NULL
    )""",
    
    """CREATE TABLE IF NOT EXISTS "auth_users_user_permissions" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "user_id" bigint NOT NULL,
        "permission_id" integer NOT NULL
    )""",
    
    """CREATE TABLE IF NOT EXISTS "auth_password_reset_tokens" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "token" varchar(64) NOT NULL UNIQUE,
        "created_at" timestamp with time zone NOT NULL,
        "expires_at" timestamp with time zone NOT NULL,
        "is_used" boolean NOT NULL,
        "user_id" bigint NOT NULL
    )""",
    
    """CREATE TABLE IF NOT EXISTS "auth_otps" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "code" varchar(6) NOT NULL,
        "session_id" uuid NOT NULL UNIQUE,
        "created_at" timestamp with time zone NOT NULL,
        "expires_at" timestamp with time zone NOT NULL,
        "is_used" boolean NOT NULL,
        "user_id" bigint NOT NULL
    )""",
    
    """CREATE TABLE IF NOT EXISTS "auth_logs" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "email" varchar(254) NOT NULL,
        "event_type" varchar(30) NOT NULL,
        "ip_address" inet NOT NULL,
        "user_agent" text NOT NULL,
        "success" boolean NOT NULL,
        "details" jsonb NOT NULL,
        "timestamp" timestamp with time zone NOT NULL,
        "user_id" bigint NULL
    )""",
    
    # Indexes
    'CREATE INDEX IF NOT EXISTS "auth_users_email_9c7e62_idx" ON "auth_users" ("email")',
    'CREATE INDEX IF NOT EXISTS "auth_users_role_8a5295_idx" ON "auth_users" ("role")',
    'CREATE INDEX IF NOT EXISTS "auth_passwo_token_076a22_idx" ON "auth_password_reset_tokens" ("token")',
    'CREATE INDEX IF NOT EXISTS "auth_otps_session_f2f8ca_idx" ON "auth_otps" ("session_id")',
    'CREATE INDEX IF NOT EXISTS "auth_otps_user_id_2268b5_idx" ON "auth_otps" ("user_id", "is_used")',
    'CREATE INDEX IF NOT EXISTS "auth_logs_email_3b60db_idx" ON "auth_logs" ("email", "timestamp")',
    'CREATE INDEX IF NOT EXISTS "auth_logs_event_t_a52c09_idx" ON "auth_logs" ("event_type", "timestamp")',
    'CREATE INDEX IF NOT EXISTS "auth_logs_ip_addr_493cba_idx" ON "auth_logs" ("ip_address", "timestamp")',
    
    # Foreign keys
    '''ALTER TABLE "auth_users_groups" DROP CONSTRAINT IF EXISTS "auth_users_groups_user_id_70322499_fk_auth_users_id"''',
    '''ALTER TABLE "auth_users_groups" ADD CONSTRAINT "auth_users_groups_user_id_70322499_fk_auth_users_id" 
       FOREIGN KEY ("user_id") REFERENCES "auth_users" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_users_groups" DROP CONSTRAINT IF EXISTS "auth_users_groups_group_id_0f75702f_fk_auth_group_id"''',
    '''ALTER TABLE "auth_users_groups" ADD CONSTRAINT "auth_users_groups_group_id_0f75702f_fk_auth_group_id" 
       FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_users_user_permissions" DROP CONSTRAINT IF EXISTS "auth_users_user_permissions_user_id_9a4c5204_fk_auth_users_id"''',
    '''ALTER TABLE "auth_users_user_permissions" ADD CONSTRAINT "auth_users_user_permissions_user_id_9a4c5204_fk_auth_users_id" 
       FOREIGN KEY ("user_id") REFERENCES "auth_users" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_users_user_permissions" DROP CONSTRAINT IF EXISTS "auth_users_user_perm_permission_id_ed9ffa4c_fk_auth_perm"''',
    '''ALTER TABLE "auth_users_user_permissions" ADD CONSTRAINT "auth_users_user_perm_permission_id_ed9ffa4c_fk_auth_perm" 
       FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_password_reset_tokens" DROP CONSTRAINT IF EXISTS "auth_password_reset_tokens_user_id_afea1893_fk_auth_users_id"''',
    '''ALTER TABLE "auth_password_reset_tokens" ADD CONSTRAINT "auth_password_reset_tokens_user_id_afea1893_fk_auth_users_id" 
       FOREIGN KEY ("user_id") REFERENCES "auth_users" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_otps" DROP CONSTRAINT IF EXISTS "auth_otps_user_id_d4c32068_fk_auth_users_id"''',
    '''ALTER TABLE "auth_otps" ADD CONSTRAINT "auth_otps_user_id_d4c32068_fk_auth_users_id" 
       FOREIGN KEY ("user_id") REFERENCES "auth_users" ("id") DEFERRABLE INITIALLY DEFERRED''',
    
    '''ALTER TABLE "auth_logs" DROP CONSTRAINT IF EXISTS "auth_logs_user_id_0860cfd0_fk_auth_users_id"''',
    '''ALTER TABLE "auth_logs" ADD CONSTRAINT "auth_logs_user_id_0860cfd0_fk_auth_users_id" 
       FOREIGN KEY ("user_id") REFERENCES "auth_users" ("id") DEFERRABLE INITIALLY DEFERRED''',
]

# Execute each statement
with connection.cursor() as cursor:
    for sql in sql_statements:
        try:
            cursor.execute(sql)
            print(f"✓ Executed: {sql[:60]}...")
        except Exception as e:
            print(f"✗ Error executing {sql[:60]}...: {e}")

print("\n✓ Authentication tables created successfully")
print("Now run: python manage.py migrate")
