import jsPDF from 'jspdf'
import logoDashboard from '../assets/LogoDashboard.png'

export interface ReceiptData {
  id: string
  title: string
  reference: string
  date: string
  amount: string
  type: 'invoice' | 'receipt'
  description?: string
  method?: string
  status?: string
}

export interface TransactionData {
  reference: string
  type: string
  date: string
  description: string
  method: string
  amount: string
  status: string
}

/**
 * Receipt Generator Service
 * Handles PDF generation for receipts and invoices with APF branding
 */
export class ReceiptGenerator {
  private static addAPFHeader(pdf: jsPDF, logoImg?: HTMLImageElement): void {
    if (logoImg) {
      // Add logo
      pdf.addImage(logoImg, 'PNG', 20, 15, 30, 30)
      
      // Header text next to logo
      pdf.setFontSize(18)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Accountancy Practitioners Forum (APF) Uganda', 60, 25)
      
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'normal')
      pdf.text('Professional Body for Forensic Accountants', 60, 32)
      pdf.text('P.O. Box 12345, Kampala, Uganda', 60, 38)
      pdf.text('Email: info@apfuganda.org | Tel: +256-XXX-XXXXXX', 60, 44)
    } else {
      // Header without logo (fallback)
      pdf.setFontSize(18)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Accountancy Practitioners Forum (APF) Uganda', 105, 25, { align: 'center' })
      
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'normal')
      pdf.text('Professional Body for Forensic Accountants', 105, 32, { align: 'center' })
      pdf.text('P.O. Box 12345, Kampala, Uganda', 105, 38, { align: 'center' })
      pdf.text('Email: info@apfuganda.org | Tel: +256-XXX-XXXXXX', 105, 44, { align: 'center' })
    }
    
    // Line separator
    pdf.setLineWidth(0.5)
    pdf.line(20, 55, 190, 55)
  }

  private static addFooter(pdf: jsPDF, yPos: number): void {
    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'italic')
    pdf.text('This is an official document generated by APF Uganda', 105, yPos, { align: 'center' })
    pdf.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 105, yPos + 6, { align: 'center' })
    
    // Watermark
    pdf.setFontSize(50)
    pdf.setTextColor(200, 200, 200)
    pdf.text('APF UGANDA', 105, 150, { align: 'center', angle: 45 })
    pdf.setTextColor(0, 0, 0) // Reset to black
  }

  private static addAmountBox(pdf: jsPDF, amount: string, yPos: number): void {
    pdf.setFillColor(240, 240, 240)
    pdf.rect(20, yPos - 5, 170, 20, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text('Total Amount:', 25, yPos + 5)
    pdf.setFontSize(16)
    pdf.setTextColor(115, 56, 160) // Purple color
    pdf.text(amount, 165, yPos + 5, { align: 'right' })
    pdf.setTextColor(0, 0, 0) // Reset to black
  }

  /**
   * Generate a receipt/invoice PDF
   */
  static async generateReceiptPDF(receipt: ReceiptData): Promise<jsPDF> {
    const pdf = new jsPDF()
    
    return new Promise<jsPDF>((resolve, reject) => {
      const logoImg = new Image()
      logoImg.crossOrigin = 'anonymous'
      
      logoImg.onload = () => {
        try {
          this.addAPFHeader(pdf, logoImg)
          
          // Document title
          pdf.setFontSize(16)
          pdf.setFont('helvetica', 'bold')
          const docTitle = receipt.type === 'invoice' ? 'OFFICIAL INVOICE' : 'OFFICIAL RECEIPT'
          pdf.text(docTitle, 105, 70, { align: 'center' })
          
          // Receipt details
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'normal')
          
          let yPos = 90
          const lineHeight = 8
          
          // Document details
          pdf.setFont('helvetica', 'bold')
          pdf.text('Document Type:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(receipt.type === 'invoice' ? 'Invoice' : 'Receipt', 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Reference Number:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(receipt.reference, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Issue Date:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(receipt.date, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Description:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          const splitDescription = pdf.splitTextToSize(receipt.title, 100)
          pdf.text(splitDescription, 70, yPos)
          yPos += (splitDescription.length - 1) * lineHeight
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Status:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text('Paid', 70, yPos)
          
          // Amount box
          yPos += 20
          this.addAmountBox(pdf, receipt.amount, yPos)
          
          // Footer
          yPos += 40
          this.addFooter(pdf, yPos)
          
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.onerror = () => {
        try {
          // Generate without logo
          this.addAPFHeader(pdf)
          // Continue with same logic...
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.src = logoDashboard
    })
  }

  /**
   * Generate a transaction receipt PDF
   */
  static async generateTransactionReceiptPDF(transaction: TransactionData): Promise<jsPDF> {
    const pdf = new jsPDF()
    
    return new Promise<jsPDF>((resolve, reject) => {
      const logoImg = new Image()
      logoImg.crossOrigin = 'anonymous'
      
      logoImg.onload = () => {
        try {
          this.addAPFHeader(pdf, logoImg)
          
          // Document title
          pdf.setFontSize(16)
          pdf.setFont('helvetica', 'bold')
          pdf.text('TRANSACTION RECEIPT', 105, 70, { align: 'center' })
          
          // Transaction details
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'normal')
          
          let yPos = 90
          const lineHeight = 8
          
          pdf.setFont('helvetica', 'bold')
          pdf.text('Transaction Type:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(transaction.type, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Reference Number:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(transaction.reference, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Transaction Date:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(transaction.date, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Description:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          const splitDescription = pdf.splitTextToSize(transaction.description, 100)
          pdf.text(splitDescription, 70, yPos)
          yPos += (splitDescription.length - 1) * lineHeight
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Payment Method:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(transaction.method, 70, yPos)
          
          yPos += lineHeight
          pdf.setFont('helvetica', 'bold')
          pdf.text('Status:', 20, yPos)
          pdf.setFont('helvetica', 'normal')
          pdf.text(transaction.status, 70, yPos)
          
          // Amount box
          yPos += 20
          this.addAmountBox(pdf, transaction.amount, yPos)
          
          // Footer
          yPos += 40
          this.addFooter(pdf, yPos)
          
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.onerror = () => {
        try {
          // Generate without logo
          this.addAPFHeader(pdf)
          // Continue with same logic...
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.src = logoDashboard
    })
  }

  /**
   * Generate a summary PDF with multiple receipts
   */
  static async generateSummaryPDF(receipts: ReceiptData[]): Promise<jsPDF> {
    const pdf = new jsPDF()
    
    return new Promise<jsPDF>((resolve, reject) => {
      const logoImg = new Image()
      logoImg.crossOrigin = 'anonymous'
      
      logoImg.onload = () => {
        try {
          this.addAPFHeader(pdf, logoImg)
          
          // Document title
          pdf.setFontSize(16)
          pdf.setFont('helvetica', 'bold')
          pdf.text('RECEIPTS & INVOICES SUMMARY', 105, 70, { align: 'center' })
          
          // Summary table
          pdf.setFontSize(10)
          let yPos = 90
          
          // Table headers
          pdf.setFont('helvetica', 'bold')
          pdf.text('Date', 20, yPos)
          pdf.text('Reference', 50, yPos)
          pdf.text('Description', 90, yPos)
          pdf.text('Amount', 160, yPos)
          
          // Line under headers
          pdf.line(20, yPos + 2, 190, yPos + 2)
          yPos += 10
          
          // Table content
          pdf.setFont('helvetica', 'normal')
          receipts.forEach((receipt) => {
            if (yPos > 250) {
              pdf.addPage()
              yPos = 30
            }
            
            pdf.text(receipt.date, 20, yPos)
            pdf.text(receipt.reference, 50, yPos)
            const shortTitle = receipt.title.length > 30 ? receipt.title.substring(0, 30) + '...' : receipt.title
            pdf.text(shortTitle, 90, yPos)
            pdf.text(receipt.amount, 160, yPos)
            yPos += 8
          })
          
          // Footer
          yPos += 20
          this.addFooter(pdf, yPos)
          
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.onerror = () => {
        try {
          // Generate without logo
          this.addAPFHeader(pdf)
          // Continue with same logic...
          resolve(pdf)
        } catch (error) {
          reject(error)
        }
      }
      
      logoImg.src = logoDashboard
    })
  }

  /**
   * Download a PDF file
   */
  static downloadPDF(pdf: jsPDF, filename: string): void {
    pdf.save(filename)
  }

  /**
   * Open PDF in new window
   */
  static viewPDF(pdf: jsPDF): boolean {
    const pdfBlob = pdf.output('blob')
    const url = URL.createObjectURL(pdfBlob)
    
    const newWindow = window.open(url, '_blank')
    if (!newWindow) {
      return false // Popup blocked
    }
    return true
  }
}

/**
 * Notification utility for user feedback
 */
export const showNotification = (message: string, type: 'success' | 'error'): void => {
  const notification = document.createElement('div')
  const bgColor = type === 'success' ? 'bg-green-600' : 'bg-red-600'
  const icon = type === 'success' 
    ? '<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>'
    : '<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>'
  
  notification.className = `fixed bottom-4 right-4 ${bgColor} text-white px-4 py-3 rounded-lg shadow-lg z-50 flex items-center gap-2 animate-in slide-in-from-right duration-300`
  notification.innerHTML = `${icon}${message}`
  document.body.appendChild(notification)
  
  setTimeout(() => {
    notification.classList.add('animate-out', 'slide-out-to-right')
    setTimeout(() => {
      if (document.body.contains(notification)) {
        document.body.removeChild(notification)
      }
    }, 300)
  }, 3000)
}