import { useState, useEffect, useCallback } from 'react'
import { 
  getNotifications, 
  getNotificationStats, 
  markNotificationAsRead as markAsReadService,
  markAllNotificationsAsRead as markAllAsReadService
} from '../services/notifications.service'
import { Notification, NotificationStats } from '../types/notification'

/**
 * Custom hook for notifications data
 * Fetches notifications from backend API
 * 
 * Notifications are event-driven and generated by backend when:
 * - User actions occur (payment, document upload, etc.)
 * - Admin actions occur (approval, rejection, etc.)
 * - System events occur (maintenance, reminders, etc.)
 */
export const useNotifications = (filter?: string) => {
  const [notifications, setNotifications] = useState<Notification[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const fetchNotifications = useCallback(async () => {
    try {
      setLoading(true)
      setError(null)
      
      const data = await getNotifications(filter)
      setNotifications(data)
    } catch (err) {
      setError('Failed to load notifications')
      console.error('Notifications error:', err)
    } finally {
      setLoading(false)
    }
  }, [filter])

  useEffect(() => {
    fetchNotifications()
  }, [fetchNotifications])

  /**
   * Mark a notification as read
   * Note: This updates backend state, not local state
   */
  const markAsRead = async (notificationId: string) => {
    try {
      const success = await markAsReadService(notificationId)
      if (success) {
        // Optimistically update local state
        setNotifications(prev => 
          prev.map(n => 
            n.id === notificationId ? { ...n, isRead: true } : n
          )
        )
      }
      return success
    } catch (err) {
      console.error('Failed to mark notification as read:', err)
      return false
    }
  }

  /**
   * Mark all notifications as read
   */
  const markAllAsRead = async () => {
    try {
      const success = await markAllAsReadService()
      if (success) {
        // Optimistically update local state
        setNotifications(prev => 
          prev.map(n => ({ ...n, isRead: true }))
        )
      }
      return success
    } catch (err) {
      console.error('Failed to mark all notifications as read:', err)
      return false
    }
  }

  /**
   * Refresh notifications
   */
  const refresh = () => {
    fetchNotifications()
  }

  return {
    notifications,
    loading,
    error,
    markAsRead,
    markAllAsRead,
    refresh
  }
}

/**
 * Custom hook for notification statistics
 */
export const useNotificationStats = () => {
  const [stats, setStats] = useState<NotificationStats>({
    total: 0,
    unread: 0,
    read: 0,
    urgent: 0,
    byType: {
      announcement: 0,
      system: 0,
      membership: 0,
      payment: 0,
      security: 0
    }
  })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true)
        setError(null)
        
        const data = await getNotificationStats()
        setStats(data)
      } catch (err) {
        setError('Failed to load notification stats')
        console.error('Notification stats error:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchStats()
  }, [])

  return {
    stats,
    loading,
    error
  }
}
