import { useState, useEffect } from 'react'
import { getRecentActivity } from '../services/activity.service'
import { Activity } from '../types/activity'

/**
 * Custom hook for recent activity data
 * Fetches user activity events from backend API
 * 
 * Activity is event-based and generated by the backend when:
 * - User performs actions (upload, payment, post, etc.)
 * - Admin performs actions (approve, reject, etc.)
 * - System events occur (renewal reminder, etc.)
 */
export const useRecentActivity = (limit: number = 10) => {
  const [activities, setActivities] = useState<Activity[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchActivity = async () => {
      try {
        setLoading(true)
        setError(null)
        
        const activityData = await getRecentActivity(limit)
        setActivities(activityData)
      } catch (err) {
        setError('Failed to load activity')
        console.error('Activity error:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchActivity()
  }, [limit])

  return {
    activities,
    loading,
    error
  }
}
