# Generated by Django 5.2.7 on 2026-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_date_of_birth_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_due_date",
            field=models.DateField(
                blank=True, help_text="Annual subscription renewal date", null=True
            ),
        ),
    ]
