# Generated by Django 4.2.9 on 2026-02-05 11:32

from django.db import migrations


def seed_payment_config(apps, schema_editor):
    """Seed initial payment configuration data."""
    PaymentConfig = apps.get_model('payments', 'PaymentConfig')
    
    # Create default membership fee configuration
    PaymentConfig.objects.get_or_create(
        key='membership_fee_ugx',
        defaults={
            'value': '50000',
            'description': 'APF membership fee in UGX (Ugandan Shillings)'
        }
    )


def reverse_seed_payment_config(apps, schema_editor):
    """Remove seeded payment configuration data."""
    PaymentConfig = apps.get_model('payments', 'PaymentConfig')
    PaymentConfig.objects.filter(key='membership_fee_ugx').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_payment_config, reverse_seed_payment_config),
    ]
