# Generated by Django 5.2.7 on 2026-01-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("payment_method", models.CharField(max_length=20)),
                ("payment_phone", models.CharField(blank=True, max_length=20)),
                ("payment_card_number", models.CharField(blank=True, max_length=50)),
                ("payment_card_expiry", models.CharField(blank=True, max_length=10)),
                ("payment_card_cvv", models.CharField(blank=True, max_length=10)),
                (
                    "payment_cardholder_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "payment_transaction_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("payment_error_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
    ("updated_at", models.DateTimeField(auto_now=True)),
    (
        "user",
        models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="applications",
            to=settings.AUTH_USER_MODEL,
        ),
    ),
],
            options={
                "verbose_name": "Membership Application",
                "verbose_name_plural": "Membership Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="application_documents/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
    ("uploaded_at", models.DateTimeField(auto_now_add=True)),
    (
        "application",
        models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="documents",
            to="applications.application",
        ),
    ),
],
            options={
                "verbose_name": "Application Document",
                "verbose_name_plural": "Application Documents",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
