# Generated by Django 5.2.7 on 2026-01-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_add_user_field_safe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="application",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("18 – 24", "18 – 24"),
                    ("25 – 34", "25 – 34"),
                    ("35 – 44", "35 – 44"),
                    ("45 – 54", "45 – 54"),
                    ("55 – 64", "55 – 64"),
                    ("65+", "65+"),
                ],
                default="18 – 24",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
