# Generated by Django 5.2.7 on 2026-02-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_add_missing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
