# Generated by Django 5.2.7 on 2026-02-02 23:15

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=["email"],
                condition=~Q(status="rejected"),
                name="uniq_application_email_not_rejected",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=["username"],
                condition=~Q(status="rejected"),
                name="uniq_application_username_not_rejected",
            ),
        ),
    ]
