# Generated by Django 5.2.7 on 2026-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_add_payment_amount"),
        ("applications", "0007_relax_payment_amount_nullable"),
    ]

    operations = []
