# Generated by Django 5.2.7 on 2026-02-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_merge_20260208_0012'),
        ('payments', '0002_seed_payment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_payment',
            field=models.ForeignKey(blank=True, help_text='Current active payment for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_application', to='payments.payment'),
        ),
    ]
