# Generated by Django 5.2.7 on 2026-02-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_merge_20260208_0012"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
