# Generated by Django 5.2.7 on 2026-02-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_current_payment'),
        ('applications', '0009_delete_document'),
    ]

    operations = [
    ]
