"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()
# Read .env file
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

SERVE_MEDIA = env.bool("SERVE_MEDIA", default=DEBUG)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "authentication",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "contacts",
    "Documents",
    "applications.apps.ApplicationsConfig",
    "notifications",
    "dashboard",
    "profiles",
    "reports",
    "adminForum",
    "AdminNotifications",
    "payments",
    "admin_management",
]

# URL Configuration
# APPEND_SLASH = False  # Re-enabled to allow Django to redirect URLs without trailing slashes

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom authentication and security middleware
    "authentication.middleware.JWTAuthenticationMiddleware",
    "authentication.middleware.SecurityHeadersMiddleware",
    "authentication.middleware.RequestLoggingMiddleware",
    # Payment middleware
    # "payments.middleware.PaymentRateLimitMiddleware",  # Temporarily disabled - requires Redis
    "payments.middleware.PaymentLoggingMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

try:
    import dj_database_url
    HAS_DJ_DATABASE_URL = True
except ImportError:
    HAS_DJ_DATABASE_URL = False

# Database Configuration - Neon PostgreSQL (Cloud)
# No localhost fallback - always use Neon database
database_url = env("DATABASE_URL", default=None)
if database_url and HAS_DJ_DATABASE_URL:
    # Parse the DATABASE_URL
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Use individual environment variables (required - no defaults)
    # Get SSL mode from environment (disable for local PostgreSQL, require for Neon)
    ssl_mode = env("DB_SSL_MODE", default="require")
    
    db_options = {}
    if ssl_mode != "disable":
        db_options["sslmode"] = ssl_mode
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),  # Required: neondb or apf_portal
            "USER": env("DB_USER"),  # Required: neondb_owner or postgres
            "PASSWORD": env("DB_PASSWORD"),  # Required
            "HOST": env("DB_HOST"),  # Required: Neon host or 127.0.0.1
            "PORT": env("DB_PORT", default="5432"),
            "OPTIONS": db_options,
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# CORS Settings
# CORS_ALLOWED_ORIGINS = env.list(

#     # "CORS_ALLOWED_ORIGINS",
#     # default=[
#     #     "http://localhost:5173",
#     #     "http://localhost:3000",
#     #     "http://localhost:3001",
#     #     "http://localhost:3002",  # Add the current frontend port
#     #     "http://127.0.0.1:5173",
#     #     "http://127.0.0.1:3000",
#     #     "http://127.0.0.1:3001",
#     #     "http://127.0.0.1:3002",  # Add the current frontend port
#     # ]
# )


CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost",
        "http://localhost:3000",
    ]
)

CORS_ALLOW_CREDENTIALS = True

# Allow all standard HTTP methods needed for authentication
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow headers needed for JWT authentication
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 'EXCEPTION_HANDLER': 'authentication.exceptions.custom_exception_handler',  # Temporarily disabled
    'UNAUTHENTICATED_USER': None,  # Return None for unauthenticated users instead of AnonymousUser
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header. Example: 'Bearer <token>'",
        }
    },
    "USE_SESSION_AUTH": False,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Default, can be extended to 30 days with remember_me
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

# Redis Cache Configuration for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'apf_portal',
        'TIMEOUT': 900,  # 15 minutes default timeout
    }
}

# Rate Limiting Configuration
RATE_LIMIT_ATTEMPTS = 5
RATE_LIMIT_WINDOW = 900  # 15 minutes in seconds

# EmailJS Configuration (Requires private key for server-side calls)
EMAILJS_SERVICE_ID = env('EMAILJS_SERVICE_ID', default='')
EMAILJS_TEMPLATE_ID_OTP = env('EMAILJS_TEMPLATE_ID_OTP', default='')
# Note: Password reset now uses the same template as OTP to save on template limits
EMAILJS_TEMPLATE_ID_APPROVAL = env('EMAILJS_TEMPLATE_ID_APPROVAL', default='')
EMAILJS_PUBLIC_KEY = env('EMAILJS_PUBLIC_KEY', default='')
EMAILJS_PRIVATE_KEY = env('EMAILJS_PRIVATE_KEY', default='')
EMAILJS_API_URL = 'https://api.emailjs.com/api/v1.0/email/send'

# Frontend URL Configuration
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

# Email Configuration (for SMTP - recommended for production)
# For development, use console backend to print emails to terminal
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='APF Portal <noreply@apfportal.com>')

SERVE_MEDIA=True

# Payment Configuration
PAYMENT_ENVIRONMENT = env('PAYMENT_ENVIRONMENT', default='sandbox')

# MTN MoMo API Configuration
MTN_API_USER = env('MTN_API_USER', default='')
MTN_API_KEY = env('MTN_API_KEY', default='')
MTN_SUBSCRIPTION_KEY = env('MTN_SUBSCRIPTION_KEY', default='')

# Airtel Money API Configuration
AIRTEL_CLIENT_ID = env('AIRTEL_CLIENT_ID', default='')
AIRTEL_CLIENT_SECRET = env('AIRTEL_CLIENT_SECRET', default='')

# Phone number encryption key (generate with: Fernet.generate_key())
PHONE_ENCRYPTION_KEY = env('PHONE_ENCRYPTION_KEY', default='')

# Payment rate limiting
PAYMENT_RATE_LIMIT_REQUESTS = env.int('PAYMENT_RATE_LIMIT_REQUESTS', default=10)
PAYMENT_RATE_LIMIT_WINDOW = env.int('PAYMENT_RATE_LIMIT_WINDOW', default=60)

# Webhook secrets
MTN_WEBHOOK_SECRET = env('MTN_WEBHOOK_SECRET', default='')
AIRTEL_WEBHOOK_SECRET = env('AIRTEL_WEBHOOK_SECRET', default='')
X_FRAME_OPTIONS = 'SAMEORIGIN'