# Generated by Django 5.2.7 on 2026-02-27 09:37

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_member_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdocument',
            name='file',
            field=models.FileField(upload_to=Documents.models.get_member_document_path),
        ),
    ]
