/**
 * TypeScript interfaces for membership registration payment system
 * Feature: membership-registration-payment
 */

/**
 * Account details data collected in step 1
 */
export interface AccountDetailsData {
  username: string;
  email: string;
  password: string;
  passwordConfirmation: string;
}

/**
 * Personal information data collected in step 2
 */
export interface PersonalInfoData {
  firstName: string;
  lastName: string;
  ageRange: string; // ISO date format (YYYY-MM-DD)
  phoneNumber: string;
  address: string;
  nationalIdNumber: string; // NIN
  icpauCertificateNumber: string; // ICPAU Practising Certificate Number
  organization?: string; // Optional - Organization/Firm
}

/**
 * Document data for uploaded files in step 3
 */
export interface DocumentData {
  id: string;
  file: File;
  fileName: string;
  fileSize: number;
  fileType: string;
  uploadStatus: 'pending' | 'uploading' | 'uploaded' | 'error';
  errorMessage?: string;
}

/**
 * Payment method types
 */
export type PaymentMethod = 'mtn' | 'airtel' | 'credit_card';

/**
 * Payment status types
 */
export type PaymentStatus = 'idle' | 'pending' | 'success' | 'completed' | 'failed' | 'cancelled' | 'timeout';

/**
 * Payment data collected in step 4
 */
export interface PaymentData {
  method: PaymentMethod;
  // Mobile money fields
  phoneNumber?: string;
  // Credit card fields
  cardNumber?: string;
  expiryDate?: string;
  cvv?: string;
  cardholderName?: string;
  // Payment processing fields
  status: PaymentStatus;
  transactionReference?: string; // Generated by payment processor
  errorMessage?: string; // Error message if payment failed
  isValidated: boolean;
}

/**
 * Complete application submission data
 */
export interface ApplicationSubmissionData {
  username: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  age_range: string;
  phoneNumber: string;
  address: string;
  nationalIdNumber: string; // NIN
  icpauCertificateNumber: string; // ICPAU Practising Certificate Number
  organization?: string; // Optional - Organization/Firm
  paymentMethod: string;
  paymentPhone?: string;
  paymentCardNumber?: string;
  paymentCardExpiry?: string;
  paymentCardCvv?: string;
  paymentCardholderName?: string;
  paymentStatus?: string;
  paymentTransactionReference?: string;
  paymentErrorMessage?: string;
  paymentAmount?: number;
  documents: DocumentData[];
}

/**
 * Validation error structure
 */
export interface ValidationError {
  field: string;
  message: string;
}

/**
 * Validation rule for form fields
 */
export interface ValidationRule {
  field: string;
  validators: ValidatorFunction[];
  errorMessage: string;
}

/**
 * Validator function type
 */
export type ValidatorFunction = (value: any) => boolean;

/**
 * API error response structure
 */
export interface APIErrorResponse {
  errors: {
    [field: string]: string[];
  };
}

/**
 * API success response structure
 */
export interface APISuccessResponse {
  id: number;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  age_range: string;
  phoneNumber: string;
  address: string;
  paymentMethod: string;
  paymentPhone?: string;
  paymentTransactionId?: string;
  paymentCardNumber?: string;
  paymentCardExpiry?: string;
  paymentCardCvv?: string;
  paymentCardholderName?: string;
  status: string;
  submittedAt: string;
  documents: any[];
}

/**
 * Session storage data structure
 */
export interface SessionStorageData {
  registrationForm: {
    currentStep: number;
    accountDetails: AccountDetailsData | null;
    personalInfo: PersonalInfoData | null;
    documents: DocumentData[];
    payment: PaymentData | null;
    lastUpdated: string; // ISO timestamp
  };
}

/**
 * Uploaded file structure
 */
export interface UploadedFile {
  id: string;
  name: string;
  size: number;
  type: string;
  url?: string;
}
