# Generated by Django 5.2.7 on 2026-02-03 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("membership", "Membership Report"),
                            ("applications", "Applications Report"),
                            ("financial", "Financial Report"),
                            ("events", "Events Report"),
                            ("compliance", "Compliance Report"),
                            ("growth", "Growth Analysis Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "fields_to_include",
                    models.JSONField(
                        default=list, help_text="List of fields to include in report"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict, help_text="Default filters for the report"
                    ),
                ),
                (
                    "chart_configs",
                    models.JSONField(
                        default=dict, help_text="Chart configuration for visualizations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False, help_text="System-generated template"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send reports to",
                    ),
                ),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "reports_schedule",
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("date_range_start", models.DateTimeField(blank=True, null=True)),
                ("date_range_end", models.DateTimeField(blank=True, null=True)),
                (
                    "filters_applied",
                    models.JSONField(
                        default=dict, help_text="Filters applied during generation"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Additional parameters used"
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("file_format", models.CharField(max_length=20)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_duration", models.DurationField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "reports_generated",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("membership", "Membership"),
                            ("applications", "Applications"),
                            ("system", "System"),
                            ("engagement", "Engagement"),
                            ("performance", "Performance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("percentage", "Percentage"),
                            ("average", "Average"),
                            ("sum", "Sum"),
                            ("ratio", "Ratio"),
                            ("growth_rate", "Growth Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measurement", max_length=50
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filters applied when calculating metric",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metric metadata"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_analytics_metric",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "name"],
                        name="reports_ana_categor_efce70_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="reports_ana_period__c5c106_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="reports_ana_calcula_95fcf0_idx"
                    ),
                ],
                "unique_together": {("name", "category", "period_start", "period_end")},
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["report_type"], name="reports_tem_report__626246_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["created_by"], name="reports_tem_created_f9d1a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["is_active"], name="reports_tem_is_acti_43b047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="reports_sch_is_acti_baace2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["created_by"], name="reports_sch_created_20281e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["generated_by"], name="reports_gen_generat_9eda54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(fields=["status"], name="reports_gen_status_40c6c3_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["created_at"], name="reports_gen_created_bdf9cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["template"], name="reports_gen_templat_17c2e5_idx"
            ),
        ),
    ]
