# Generated by Django 5.2.7 on 2026-02-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_usernotification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usernotification",
            new_name="notificatio_user_id_776dd3_idx",
            old_name="notificatio_user_id_f8e9a3_idx",
        ),
        migrations.RenameIndex(
            model_name="usernotification",
            new_name="notificatio_user_id_ce6926_idx",
            old_name="notificatio_user_id_a1b2c3_idx",
        ),
    ]
